### ISSUE TITLE
Upgrade to newer PDMats.jl

### ISSUE THREAD

**Issue by simonbyrne** [JuliaStats/ConjugatePriors.jl#15]
Due to the upper bound, having this package installed causes a Distributions to break.

cf https://github.com/JuliaStats/Distributions.jl/issues/560

**Comment by ararslan** [comment]
Related to #10 I believe

**Comment by ValdarT** [comment]
This package still downgrades PDMats, Distributions, and StatsFuns. Any plans of bringing it up to date or reintegrating into Distributions any time soon?

**Comment by ararslan** [comment]
@ValdarT Should be good on the master branch, and with the impending v0.2.0: https://github.com/JuliaLang/METADATA.jl/pull/10159

**Comment by ValdarT** [comment]
Thanks! Everything is indeed good after a Pkg.checkout.

**Comment by ararslan** [comment]
Fantastic! And v0.2.0 has just been merged into METADATA, so you should be able to `Pkg.update()` then `Pkg.free("ConjugatePriors")` to get the latest tagged version.

**Comment by ararslan** [comment]
This issue no longer applies so I'm going to close it.
