### ISSUE TITLE
Exporting distribution types and methods

### ISSUE THREAD

**Issue by hassaku** [JuliaStats/ConjugatePriors.jl#2]
Hi, I'm a Julia newbie.

I understand that it's necessary to export distribution types and methods in ConjugatePriors.jl for calling them without prefix like "ConjugatePriors.NormalWishart".

What do you think this idea and the necessity of PR for them?

**Comment by kmsquire** [comment]
I suspect that not many people have been using this package, and that exporting the distributions and related functions was probably an oversight.  Please do submit a PR.

**Comment by hassaku** [comment]
Thanks for your comment.

There are methods with the same name. And I have read the following discussion.
https://github.com/JuliaLang/julia/issues/4345

I guess I shouldn't export such methods because they conflict with JuliaStats/Distributions used by many people. The way to call them by importing like this (https://github.com/sbos/DirichletProcessMixtures.jl/pull/2/files#diff-419170f3cc9265a07db822a9d8328242R7) is better.

So, I just close this issue. Thanks.
