### ISSUE TITLE
disagreement in `mode` of NormalInverseChisq and NormalInverseGamma

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaStats/ConjugatePriors.jl#20]
These are two equivalent parametrizations of the conjugate prior for a normal with unknown mean and variance.  Both are based on Murphy, and the mode for NIX2 was taken directly from Murphy, while the mode for NIG isn't given explicitly.  

```julia
julia> using Distributions

julia> using ConjugatePriors: NormalInverseChisq, NormalInverseGamma

julia> d = NormalInverseGamma(0., 1., 2, 2)
ConjugatePriors.NormalInverseGamma{Float64}(mu=0.0, v0=1.0, shape=2.0, scale=2.0)

julia> d2 = NormalInverseChisq(d)
ConjugatePriors.NormalInverseChisq{Float64}(μ=0.0, σ2=1.0, κ=1.0, ν=4.0)

julia> mode(d2)
(0.0, 1.3333333333333333)

julia> mode(d)
(0.0, 0.6666666666666666)
```

They _do_ agree if the formula that Murphy gives for the mode of the marginal posterior of the variance is used:

```julia
julia> margmode(d::NormalInverseChisq) = d.ν*d.σ2 / (d.ν+2)
margmode (generic function with 1 method)

julia> margmode(d2)
0.6666666666666666
```

Which suggests to me that the NIG formula is also using the marginal posterior.

**Comment by mschauer** [comment]
Ref https://github.com/scipy/scipy/pull/6739

**Comment by kleinschmidt** [comment]
...which is apparently based on the julia implementation: https://github.com/scipy/scipy/issues/6528#issuecomment-252439066

**Comment by mschauer** [comment]
Yes, just to give them a head up.
